
services:
  db:
    image: postgres:17.4
    restart: always
    container_name: postgres
    ports:
      - 7400:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata2:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - public

  discovery:
    build: ./discovery-service
    image: discovery-service:latest
    restart: always
    container_name: discovery
    ports:
      - "8761:8761"
    environment:
      - DISCOVERY_SERVICE_NAME=discovery-service
      - DISCOVERY_SERVICE_PORT=8761
    networks:
      - public

  paiement:
    build: ./paiement-service 
    image: paiement-service:latest
    restart: always
    container_name: paiement
    depends_on:
      - db
      - discovery
    expose:
      - "7070"
    environment:
      - PAIEMENT_SERVICE_NAME=paiement-service
      - PAIEMENT_SERVICE_PORT=7070
      - PAIEMENT_SERVICE_DB_URL=db:5432/paiement
      - PAIEMENT_SERVICE_DB_USERNAME=user_paiement
      - PAIEMENT_SERVICE_DB_PASSWORD=123456
      - PAIEMENT_SERVICE_EUREKA_URL=http://discovery:8761/eureka
      - PAIEMENT_SERVICE_EUREKA_SWAGGER_PATH=/api/paiements/swagger-ui.html
      - PAIEMENT_SERVICE_EUREKA_API_DOCS_PATH=/api/paiements/v3/api-docs
    networks:
      - public
 
  reservation:
    build: ./reservation-service 
    image: reservation-service:latest
    restart: always
    container_name: reservation
    ports:
      - "8082:8082"
    depends_on:
      - db
      - discovery
    environment:
      - RESERVATION_SERVICE_NAME=reservation-service
      - RESERVATION_SERVICE_PORT=8082
      - RESERVATION_SERVICE_DB_URL=db:5432/postgres
      - RESERVATION_SERVICE_DB_USERNAME=postgres
      - RESERVATION_SERVICE_DB_PASSWORD=postgres
      - RESERVATION_SERVICE_EUREKA_URL=http://discovery:8761/eureka
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - public


  gateway:
    build: ./gateway-service
    image: gateway-service:latest
    restart: always
    container_name: gateway
    ports:
      - "8888:8888"
    depends_on:
      - paiement
      - discovery
    environment:
      - GATEWAY_SERVICE_NAME=gateway-service
      - GATEWAY_SERVICE_PORT=8888
      - GATEWAY_SERVICE_EUREKA_URL=http://discovery:8761/eureka
  
    networks:
      - public

volumes:
  pgdata2:
    driver: local

networks:
  public:
    external: true
