server:
  port: ${PAIEMENT_SERVICE_PORT} #7070

spring:
  application:
    name: ${PAIEMENT_SERVICE_NAME} #paiement-service

  data:
    rest:
      base-path: /api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PAIEMENT_SERVICE_DB_URL} #localhost:5432/paiement
    username: ${PAIEMENT_SERVICE_DB_USERNAME} #user_cdubon
    password: ${PAIEMENT_SERVICE_DB_PASSWORD} #123456

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      platform: postgres

  profiles:
    active: dev

  cloud:
    discovery:
      enabled: true
    config:
      enabled: false

  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone:  ${PAIEMENT_SERVICE_EUREKA_URL} #http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: ${PAIEMENT_SERVICE_EUREKA_SWAGGER_PATH} #/api/paiements/swagger-ui.html
    enabled: true
  api-docs:
    path: ${PAIEMENT_SERVICE_EUREKA_API_DOCS_PATH} #/api/paiements/v3/api-docs

debug: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
