server:
  port: ${GATEWAY_SERVICE_PORT} #8888

spring:
  application:
    name: ${GATEWAY_SERVICE_NAME} #gateway-service

  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: false
#          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        #- id: ${SPRING_CLOUD_GATEWAY_ROUTES_0_ID} #reservation-service
         # uri: ${SPRING_CLOUD_GATEWAY_ROUTES_0_URI} #lb://RESERVATION-SERVICE
          #predicates:
           # - ${SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0} #Path=/api/reservations/**

        - id: paiement-service #paiement-service
          uri: lb://PAIEMENT-SERVICE #lb://PAIEMENT-SERVICE
          predicates:
            - Path=/api/paiements/** #Path=/api/paiements/**

        - id: fleet-service
          uri: lb://FLEET-SERVICE
          predicates:
            - Path=/vehicle/**, /trip/**, /driver/**


eureka:
  client:
    service-url:
      defaultZone:  ${GATEWAY_SERVICE_EUREKA_URL} #http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
