server:
  port: ${GATEWAY_SERVICE_PORT} #8888

spring:
  application:
    name: ${GATEWAY_SERVICE_NAME} #gateway-service

  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: false
#          lower-case-service-id: true

      routes:
        - id: ${SPRING_CLOUD_GATEWAY_ROUTES_0_ID} #reservation-service
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_0_URI} #lb://RESERVATION-SERVICE
          predicates:
            - ${SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0} #Path=/api/reservations/**

        - id: ${SPRING_CLOUD_GATEWAY_ROUTES_1_ID} #paiement-service
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_1_URI} #lb://PAIEMENT-SERVICE
          predicates:
            - ${SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0} #Path=/api/paiements/**



eureka:
  client:
    service-url:
      defaultZone:  ${PAIEMENT_SERVICE_EUREKA_URL} #http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
