server:
  port: ${DISCOVERY_SERVICE_PORT} #8761


spring:
  application:
    name: ${DISCOVERY_SERVICE_NAME} #discovery-service

  cloud:
    discovery:
      enabled: true

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
